scheduler:
  jobs:
    rejected-timeout-ms: 300000 # 5 min, should be configured according to worker's timeouts
    rejected-update-period-ms: 60000 # 1 min
  kafka:
    broker-url: ${SCHEDULER_KAFKA_BROKER_URL:localhost:8097}
    reconnect-backoff-ms: 100
    reconnect-backoff-max-ms: 10000
    jobs-topic-prefix: pending-
    running-topic-name: running
    finished-topic-name: finished
    producer-acks: 1
    consumer-group: schedulers
  kafka-admin:
    broker-url: ${scheduler.kafka.broker-url}
    reconnect-backoff-ms: ${scheduler.kafka.reconnect-backoff-ms}
    reconnect-backoff-max-ms: ${scheduler.kafka.reconnect-backoff-max-ms}
    replication-factor: 2
    jobs-topics-prefix: ${scheduler.kafka.jobs-topic-prefix}
    jobs-topics-partitions: 2
    running-topic-name: ${scheduler.kafka.running-topic-name}
    running-topic-partitions: 2
    finished-topic-name: ${scheduler.kafka.finished-topic-name}
    finished-topic-partitions: 2

spring:
  datasource:
    url: jdbc:postgresql://${SCHEDULER_POSTGRES_URL:localhost:5432}/dotnet-scripts-scheduler
    username: dotnet-scripts-scheduler
    password: 1234
    hikari:
      maximum-pool-size: 12
      minimum-idle: 1
      connection-test-query: SELECT 1
      validation-timeout: 3500
      max-lifetime: 1200000
      idle-timeout: 13000
      connection-timeout: 100000
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc.batch_size: 10
        order_updates: true
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  packages-to-scan: >
    com.naumov.dotnetscriptsscheduler.controller,
    com.naumov.dotnetscriptsscheduler.dto.rest.rq,
    com.naumov.dotnetscriptsscheduler.dto.rest.rs
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
