spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dotnet-scripts-scheduler
    username: dotnet-scripts-scheduler
    password: 1234
    hikari:
      maximum-pool-size: 12
      minimum-idle: 1
      connection-test-query: SELECT 1
      validation-timeout: 3500
      max-lifetime: 1200000
      idle-timeout: 13000
      connection-timeout: 100000
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate # TODO change to none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 10
        order_updates: true
        order_inserts: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml